import { DecisionBadge } from "@/components/actions/decision-badge";
import type { Policy } from "@/lib/types";
import { PolicyCategoryBadge, PolicyStatusBadge } from "./policy-badges";

function formatAction(action: string) {
  return action.split("_").join(" ");
}

export function PolicyTable({ policies }: { policies: Policy[] }) {
  if (policies.length === 0) {
    return <div className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center shadow-sm"><span className="mx-auto flex size-10 items-center justify-center rounded-xl bg-indigo-50 text-indigo-700">+</span><h3 className="mt-4 text-base font-semibold text-slate-900">No policies yet</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-500">Upload a company policy document to begin extracting structured rules for review.</p></div>;
  }

  return <>
    <div className="hidden overflow-hidden rounded-2xl border border-slate-200/90 bg-white shadow-[0_1px_2px_rgba(15,23,42,0.03),0_10px_28px_rgba(15,23,42,0.025)] lg:block"><table className="w-full text-left"><thead className="border-b border-slate-200/80 bg-slate-50/80 text-[11px] font-semibold uppercase tracking-[0.08em] text-slate-500"><tr><th className="px-5 py-3.5">Policy</th><th className="px-4 py-3.5">Category</th><th className="px-4 py-3.5">Enforcement</th><th className="px-4 py-3.5">Status</th><th className="px-4 py-3.5">Scope</th><th className="px-5 py-3.5">Source</th></tr></thead><tbody className="divide-y divide-slate-100/90">{policies.map((policy) => <tr key={policy.policy_id} className="align-top transition-colors duration-150 hover:bg-indigo-50/[0.35]"><td className="px-5 py-4.5"><p className="font-semibold tracking-[-0.015em] text-slate-900">{policy.name}</p><p className="mt-1 font-mono text-xs text-slate-500">{formatAction(policy.action)} · v{policy.version} · priority {policy.priority}</p></td><td className="px-4 py-4.5"><PolicyCategoryBadge category={policy.category} /></td><td className="px-4 py-4.5"><DecisionBadge decision={policy.decision} />{policy.approval_role && <p className="mt-1.5 text-xs capitalize text-slate-500">{policy.approval_role.replace("_", " ")}</p>}</td><td className="px-4 py-4.5"><PolicyStatusBadge status={policy.status} /></td><td className="px-4 py-4.5"><p className="text-sm text-slate-700">{policy.subject.roles.join(", ")}</p><p className="mt-1 text-xs text-slate-500">{policy.conditions.length === 0 ? "Always applies" : `${policy.conditions.length} condition${policy.conditions.length === 1 ? "" : "s"}`}</p></td><td className="px-5 py-4.5"><p className="font-mono text-xs text-slate-600">{policy.source_doc ?? "No source document"}</p></td></tr>)}</tbody></table></div>
    <div className="space-y-4 lg:hidden">{policies.map((policy) => <article key={policy.policy_id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-900">{policy.name}</h3><p className="mt-1 font-mono text-xs text-slate-500">{formatAction(policy.action)} · v{policy.version}</p></div><PolicyStatusBadge status={policy.status} /></div><div className="mt-4 flex flex-wrap gap-2"><PolicyCategoryBadge category={policy.category} /><DecisionBadge decision={policy.decision} /></div><dl className="mt-4 grid grid-cols-2 gap-x-4 gap-y-3 border-t border-slate-100 pt-4 text-sm"><div><dt className="text-slate-500">Bound roles</dt><dd className="mt-1 text-slate-700">{policy.subject.roles.join(", ")}</dd></div><div><dt className="text-slate-500">Conditions</dt><dd className="mt-1 text-slate-700">{policy.conditions.length === 0 ? "Always applies" : `${policy.conditions.length} condition${policy.conditions.length === 1 ? "" : "s"}`}</dd></div><div><dt className="text-slate-500">Priority</dt><dd className="mt-1 text-slate-700">{policy.priority}</dd></div><div><dt className="text-slate-500">Source</dt><dd className="mt-1 font-mono text-xs text-slate-700">{policy.source_doc ?? "Not available"}</dd></div></dl></article>)}</div>
  </>;
}
