"use client";

import { useState } from "react";
import { DecisionBadge } from "@/components/actions/decision-badge";
import type { Decision, Policy } from "@/lib/types";
import { PolicyCategoryBadge } from "./policy-badges";

export type ReviewStatus = "pending" | "confirmed" | "rejected";

function ReviewBadge({ status }: { status: ReviewStatus }) {
  const content = { pending: ["Awaiting review", "bg-amber-50 text-amber-800 ring-amber-600/20"], confirmed: ["Confirmed", "bg-emerald-50 text-emerald-700 ring-emerald-600/20"], rejected: ["Rejected", "bg-rose-50 text-rose-700 ring-rose-600/20"] }[status];
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ring-inset ${content[1]}`}>{content[0]}</span>;
}

export function RuleReviewCard({ policy, reviewStatus, onStatusChange, onEdit }: { policy: Policy; reviewStatus: ReviewStatus; onStatusChange: (status: ReviewStatus) => void; onEdit: (policy: Policy) => void }) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(policy);
  const conditionText = policy.conditions.length === 0 ? "Always applies" : policy.conditions.map((condition) => `${condition.field} ${condition.operator} ${condition.value}${condition.unit ? ` ${condition.unit}` : ""}`).join(" · ");

  function saveEdit() { onEdit(draft); setEditing(false); }

  return <article className="rounded-2xl border border-slate-200/90 bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.03),0_10px_28px_rgba(15,23,42,0.025)]"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><PolicyCategoryBadge category={policy.category} /><ReviewBadge status={reviewStatus} /></div><h3 className="mt-3 text-lg font-semibold tracking-[-0.02em] text-slate-950">{policy.name}</h3><p className="mt-1 font-mono text-xs text-slate-500">{policy.policy_id} · {policy.source_doc ?? "Source unavailable"}</p></div><DecisionBadge decision={policy.decision} /></div>
    <div className="mt-6 grid gap-4 lg:grid-cols-2"><section className="rounded-xl border border-slate-100 bg-slate-50/80 p-5"><p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-slate-500">Original policy text</p><blockquote className="mt-3 border-l-2 border-indigo-200 pl-3 text-sm leading-6 text-slate-700">“{policy.original_text ?? "No original source text is available."}”</blockquote></section><section className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-slate-500">Structured rule</p><dl className="mt-4 grid grid-cols-2 gap-x-4 gap-y-3 text-sm"><div><dt className="text-slate-500">Action</dt><dd className="mt-1 font-mono text-slate-800">{policy.action}</dd></div><div><dt className="text-slate-500">Scope</dt><dd className="mt-1 text-slate-800">{policy.subject.roles.join(", ")}</dd></div><div className="col-span-2"><dt className="text-slate-500">Conditions</dt><dd className="mt-1 text-slate-800">{conditionText}</dd></div>{policy.approval_role && <div><dt className="text-slate-500">Required approval</dt><dd className="mt-1 capitalize text-slate-800">{policy.approval_role.replace("_", " ")}</dd></div>}<div><dt className="text-slate-500">Priority</dt><dd className="mt-1 text-slate-800">{policy.priority}</dd></div></dl></section></div>
    {reviewStatus === "pending" && <div className="mt-5 flex flex-wrap gap-3 border-t border-slate-100 pt-4"><button type="button" onClick={() => onStatusChange("confirmed")} className="h-10 rounded-xl bg-emerald-600 px-4 text-sm font-semibold text-white shadow-sm shadow-emerald-100 hover:bg-emerald-700">Confirm rule</button><button type="button" onClick={() => setEditing(true)} className="h-10 rounded-xl border border-slate-300 bg-white px-4 text-sm font-semibold text-slate-700 hover:bg-slate-50">Edit</button><button type="button" onClick={() => onStatusChange("rejected")} className="h-10 rounded-xl px-4 text-sm font-semibold text-rose-700 hover:bg-rose-50">Reject</button></div>}
    {editing && <div className="mt-5 rounded-xl border border-indigo-200 bg-indigo-50/50 p-4"><h4 className="font-semibold text-slate-900">Edit structured rule</h4><p className="mt-1 text-sm text-slate-600">Changes are local to this demo and are not saved to a backend.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Rule name<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-indigo-500" /></label><label className="text-sm font-medium text-slate-700">Action<input value={draft.action} onChange={(event) => setDraft({ ...draft, action: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-indigo-500" /></label><label className="text-sm font-medium text-slate-700">Decision<select value={draft.decision} onChange={(event) => setDraft({ ...draft, decision: event.target.value as Decision })} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-indigo-500"><option value="allow">Allow</option><option value="block">Block</option><option value="requires_approval">Requires approval</option></select></label><label className="text-sm font-medium text-slate-700">Priority<input type="number" value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: Number(event.target.value) })} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-indigo-500" /></label></div><div className="mt-4 flex gap-3"><button type="button" onClick={saveEdit} className="rounded-lg bg-indigo-600 px-3.5 py-2 text-sm font-semibold text-white hover:bg-indigo-700">Save local changes</button><button type="button" onClick={() => { setDraft(policy); setEditing(false); }} className="rounded-lg px-3.5 py-2 text-sm font-semibold text-slate-600 hover:bg-white">Cancel</button></div></div>}
  </article>;
}
