from .models.gateway_models import Policy, PolicyCondition, PolicySubject

SOURCE_REFUNDS = "doc_001"
SOURCE_CUSTOMER_DATA = "doc_002"
SOURCE_ORDERS = "doc_003"

POLICIES = [
    Policy(
        policy_id="refund_gift_card_001",
        name="Gift card purchases cannot receive cash refunds",
        category="payments",
        subject=PolicySubject(roles=["ai_agent"]),
        action="issue_refund",
        conditions=[PolicyCondition(field="payment_method", operator="==", value="gift_card")],
        decision="block",
        priority=110,
        source_doc=SOURCE_REFUNDS,
        original_text="Gift card purchases are never refunded in cash; issue store credit only.",
    ),
    Policy(
        policy_id="refund_finance_001",
        name="Refunds above $500 require finance director approval",
        category="payments",
        subject=PolicySubject(roles=["ai_agent"]),
        action="issue_refund",
        conditions=[PolicyCondition(field="amount", operator=">", value=500, unit="USD")],
        decision="requires_approval",
        approval_role="finance_director",
        priority=100,
        source_doc=SOURCE_REFUNDS,
        original_text="Refunds over $500 require sign-off from the finance director.",
    ),
    Policy(
        policy_id="refund_manager_001",
        name="Refunds above $100 require shift manager approval",
        category="payments",
        subject=PolicySubject(roles=["ai_agent"]),
        action="issue_refund",
        conditions=[PolicyCondition(field="amount", operator=">", value=100, unit="USD")],
        decision="requires_approval",
        approval_role="manager",
        priority=90,
        source_doc=SOURCE_REFUNDS,
        original_text="Refunds above $100 need shift manager sign-off.",
    ),
    Policy(
        policy_id="discount_limit_001",
        name="Desk discounts cannot exceed 20 percent",
        category="pricing",
        subject=PolicySubject(roles=["ai_agent"]),
        action="apply_discount",
        conditions=[PolicyCondition(field="discount_percent", operator=">", value=20, unit="percent")],
        decision="block",
        priority=90,
        source_doc=SOURCE_REFUNDS,
        original_text="No discount may be larger than 20%.",
    ),
    Policy(
        policy_id="credit_application_001",
        name="Assistants cannot access credit-account applications",
        category="customer_data",
        subject=PolicySubject(roles=["ai_agent"]),
        action="get_credit_application",
        decision="block",
        priority=100,
        source_doc=SOURCE_CUSTOMER_DATA,
        original_text="The assistant must never read credit-account applications.",
    ),
    Policy(
        policy_id="customer_export_001",
        name="Customer lists cannot be exported",
        category="customer_data",
        subject=PolicySubject(roles=["ai_agent"]),
        action="export_customer_list",
        decision="block",
        priority=100,
        source_doc=SOURCE_CUSTOMER_DATA,
        original_text="Customer lists must never be exported.",
    ),
    Policy(
        policy_id="shipping_update_status_001",
        name="Shipping addresses can change only before courier handoff",
        category="orders",
        subject=PolicySubject(roles=["ai_agent"]),
        action="update_shipping_address",
        conditions=[PolicyCondition(field="fulfillment_status", operator="==", value="dispatched")],
        decision="block",
        priority=100,
        source_doc=SOURCE_ORDERS,
        original_text="Once an order is dispatched, no address changes are allowed.",
    ),
    Policy(
        policy_id="order_cancel_status_001",
        name="Orders cannot be cancelled after courier handoff",
        category="orders",
        subject=PolicySubject(roles=["ai_agent"]),
        action="cancel_order",
        conditions=[PolicyCondition(field="fulfillment_status", operator="==", value="dispatched")],
        decision="block",
        priority=100,
        source_doc=SOURCE_ORDERS,
        original_text="Once an order is dispatched, no cancellations are allowed.",
    ),
]

POLICY_BY_ID = {policy.policy_id: policy for policy in POLICIES}
