// Mock data for building the UI before the backend exists.
// Populate with sample Policy / AgentAction / GatewayDecision objects as pages get built.

import type { AgentAction, GatewayDecision, Policy } from "./types";

export const mockPolicies: Policy[] = [
  { policy_id: "refund_standard_001", name: "Standard refund authorization", category: "payments", subject: { roles: ["support_agent", "ai_agent"] }, action: "issue_refund", conditions: [{ field: "amount", operator: "<=", value: 100, unit: "USD" }], decision: "allow", priority: 70, version: 1, status: "active", source_doc: "doc_001", original_text: "Support staff and the assistant can issue refunds up to $100 without asking anyone." },
  { policy_id: "refund_manager_001", name: "Manager approval for larger refunds", category: "payments", subject: { roles: ["support_agent", "ai_agent"] }, action: "issue_refund", conditions: [{ field: "amount", operator: ">", value: 100, unit: "USD" }], decision: "requires_approval", approval_role: "manager", priority: 90, version: 1, status: "active", source_doc: "doc_001", original_text: "Anything above $100 needs sign-off from a shift manager before the money goes out." },
  { policy_id: "refund_finance_001", name: "Finance approval for high-value refunds", category: "payments", subject: { roles: ["support_agent", "ai_agent"] }, action: "issue_refund", conditions: [{ field: "amount", operator: ">", value: 500, unit: "USD" }], decision: "requires_approval", approval_role: "finance_director", priority: 100, version: 1, status: "active", source_doc: "doc_001", original_text: "If a refund is above $500 it must go to Priya personally." },
  { policy_id: "gift_card_refund_001", name: "Gift card cash refund restriction", category: "payments", subject: { roles: ["support_agent", "ai_agent"] }, action: "issue_refund", conditions: [{ field: "payment_method", operator: "==", value: "gift_card" }], decision: "block", priority: 100, version: 1, status: "active", source_doc: "doc_001", original_text: "We do NOT refund gift card purchases in cash, ever. Store credit only." },
  { policy_id: "discount_limit_001", name: "Desk discount limit", category: "pricing", subject: { roles: ["support_agent", "ai_agent"] }, action: "apply_discount", conditions: [{ field: "discount_percent", operator: ">", value: 20, unit: "percent" }], decision: "block", priority: 90, version: 1, status: "active", source_doc: "doc_001", original_text: "Nobody on the desk may apply a discount larger than 20% to any item." },
  { policy_id: "credit_application_001", name: "Credit application access restriction", category: "customer_data", subject: { roles: ["support_agent", "ai_agent"] }, action: "get_credit_application", conditions: [], decision: "block", priority: 100, version: 1, status: "active", source_doc: "doc_002", original_text: "The assistant must never read, summarise, or forward anything from a credit application." },
  { policy_id: "customer_export_001", name: "Customer list export restriction", category: "customer_data", subject: { roles: ["marketing_agent", "ai_agent"] }, action: "export_customer_list", conditions: [], decision: "block", priority: 100, version: 1, status: "active", source_doc: "doc_002", original_text: "Customer lists must never be exported, emailed, or pasted into any external tool." },
  { policy_id: "third_party_disclosure_001", name: "Third-party customer disclosure restriction", category: "customer_data", subject: { roles: ["order_agent", "ai_agent"] }, action: "disclose_order_details", conditions: [], decision: "block", priority: 100, version: 1, status: "active", source_doc: "doc_002", original_text: "Do not confirm whether a person is a customer to any third party." },
  { policy_id: "return_fee_001", name: "Return shipping fee waiver review", category: "orders", subject: { roles: ["order_agent", "ai_agent"] }, action: "waive_return_fee", conditions: [], decision: "requires_approval", approval_role: "manager", priority: 90, version: 1, status: "active", source_doc: "doc_003", original_text: "The waiver must be applied by a human staff member, not the assistant." },
  { policy_id: "out_of_hours_message_001", name: "Out-of-hours message approval", category: "communication", subject: { roles: ["order_agent", "support_agent", "ai_agent"] }, action: "send_message", conditions: [{ field: "local_hour", operator: "in", value: "outside_8_to_20", unit: "hours" }], decision: "requires_approval", approval_role: "manager", priority: 80, version: 1, status: "pending_review", source_doc: "doc_003", original_text: "Anything urgent outside those hours needs a manager to approve the send." },
  { policy_id: "records_request_001", name: "Customer records request review", category: "customer_data", subject: { roles: ["support_agent", "ai_agent"] }, action: "request_customer_records", conditions: [], decision: "requires_approval", approval_role: "manager", priority: 90, version: 1, status: "pending_review", source_doc: "doc_002", original_text: "Requests for a copy of a customer's records require identity verification by a manager." },
  { policy_id: "apology_compensation_001", name: "Apology compensation review", category: "communication", subject: { roles: ["support_agent", "ai_agent"] }, action: "offer_compensation", conditions: [], decision: "requires_approval", approval_role: "manager", priority: 90, version: 1, status: "pending_review", source_doc: "doc_003", original_text: "The assistant must not offer refunds, discounts, or free items as an apology gesture." },
  { policy_id: "shipping_address_001", name: "Pre-dispatch address changes", category: "orders", subject: { roles: ["order_agent", "ai_agent"] }, action: "update_shipping_address", conditions: [{ field: "fulfillment_status", operator: "!=", value: "dispatched" }], decision: "allow", priority: 80, version: 1, status: "active", source_doc: "doc_003", original_text: "Shipping address changes are fine before dispatch." },
];

export const mockActions: AgentAction[] = [
  { action_id: "act_1001", agent_id: "support_agent", actor_role: "ai_agent", tool: "issue_refund", action: "issue_refund", arguments: { customer_id: "cust_193", amount: 80, currency: "USD", days_since_purchase: 14 }, context: { conversation_id: "conv_4821", reason: "returned table lamp" }, timestamp: "2026-09-21T11:32:00Z" },
  { action_id: "act_1002", agent_id: "order_agent", actor_role: "ai_agent", tool: "update_shipping_address", action: "update_shipping_address", arguments: { order_id: "ord_672", fulfillment_status: "processing" }, context: { conversation_id: "conv_4822", reason: "customer requested address correction" }, timestamp: "2026-09-21T11:38:00Z" },
  { action_id: "act_1003", agent_id: "support_agent", actor_role: "ai_agent", tool: "issue_refund", action: "issue_refund", arguments: { customer_id: "cust_207", amount: 150, currency: "USD" }, context: { conversation_id: "conv_4823", reason: "defective coffee maker" }, timestamp: "2026-09-21T11:45:00Z" },
  { action_id: "act_1004", agent_id: "support_agent", actor_role: "ai_agent", tool: "apply_discount", action: "apply_discount", arguments: { customer_id: "cust_088", discount_percent: 25, promo_code: null }, context: { conversation_id: "conv_4824", reason: "apology for delayed delivery" }, timestamp: "2026-09-21T11:51:00Z" },
  { action_id: "act_1005", agent_id: "support_agent", actor_role: "ai_agent", tool: "issue_refund", action: "issue_refund", arguments: { customer_id: "cust_129", amount: 60, payment_method: "gift_card", refund_method: "cash" }, context: { conversation_id: "conv_4825", reason: "gift card purchase" }, timestamp: "2026-09-21T11:58:00Z" },
  { action_id: "act_1006", agent_id: "order_agent", actor_role: "ai_agent", tool: "waive_return_fee", action: "waive_return_fee", arguments: { customer_id: "cust_314", amount: 9, currency: "USD" }, context: { conversation_id: "conv_4826", reason: "package arrived late" }, timestamp: "2026-09-21T12:04:00Z" },
  { action_id: "act_1007", agent_id: "order_agent", actor_role: "ai_agent", tool: "get_order_status", action: "disclose_order_details", arguments: { customer_id: "cust_254", requester_relationship: "spouse" }, context: { conversation_id: "conv_4827", reason: "third-party caller asked what was ordered" }, timestamp: "2026-09-21T12:09:00Z" },
  { action_id: "act_1008", agent_id: "support_agent", actor_role: "ai_agent", tool: "get_credit_application", action: "get_credit_application", arguments: { customer_id: "cust_061" }, context: { conversation_id: "conv_4828", reason: "answer financing question" }, timestamp: "2026-09-21T12:15:00Z" },
  { action_id: "act_1009", agent_id: "marketing_agent", actor_role: "ai_agent", tool: "export_customer_list", action: "export_customer_list", arguments: { destination: "partner_campaign" }, context: { reason: "partner campaign" }, timestamp: "2026-09-21T12:21:00Z" },
  { action_id: "act_1010", agent_id: "support_agent", actor_role: "ai_agent", tool: "issue_refund", action: "issue_refund", arguments: { customer_id: "cust_390", amount: 600, currency: "USD" }, context: { conversation_id: "conv_4829", reason: "sectional sofa return" }, timestamp: "2026-09-21T12:28:00Z" },
];

export const mockDecisions: GatewayDecision[] = [
  { decision: "allow", action_id: "act_1001", policy_ids: ["refund_standard_001"], reason: "Refund is within the $100 agent authorization limit and inside the 30-day window." },
  { decision: "allow", action_id: "act_1002", policy_ids: ["shipping_address_001"], reason: "The order has not been dispatched, so the shipping address may be updated." },
  { decision: "requires_approval", action_id: "act_1003", policy_ids: ["refund_manager_001"], reason: "Refund amount exceeds the $100 agent authorization limit.", required_approval: "manager", expires_at: "2026-09-21T20:00:00Z" },
  { decision: "block", action_id: "act_1004", policy_ids: ["discount_limit_001"], reason: "The requested 25% discount exceeds the 20% desk limit." },
  { decision: "block", action_id: "act_1005", policy_ids: ["gift_card_refund_001"], reason: "Gift card purchases may receive store credit only, never a cash refund." },
  { decision: "requires_approval", action_id: "act_1006", policy_ids: ["return_fee_001"], reason: "Return shipping fee waivers are human-only and must be reviewed.", required_approval: "manager", expires_at: "2026-09-21T20:00:00Z" },
  { decision: "block", action_id: "act_1007", policy_ids: ["third_party_disclosure_001"], reason: "Customer order information cannot be disclosed to a third party." },
  { decision: "block", action_id: "act_1008", policy_ids: ["credit_application_001"], reason: "AI assistants may not access credit account applications." },
  { decision: "block", action_id: "act_1009", policy_ids: ["customer_export_001"], reason: "Customer lists must never be exported to external tools." },
  { decision: "requires_approval", action_id: "act_1010", policy_ids: ["refund_finance_001", "refund_manager_001"], reason: "The $600 refund exceeds the finance-director approval threshold.", required_approval: "finance_director", expires_at: "2026-09-21T20:00:00Z" },
];
