import Link from "next/link";
import { DecisionBadge } from "@/components/actions/decision-badge";
import { StatCard } from "@/components/ui/stat-card";
import { mockActions, mockDecisions, mockPolicies } from "@/lib/mock-data";

const titleForAction = (action: string) => action.split("_").map((word) => word[0].toUpperCase() + word.slice(1)).join(" ");
const formatTime = (timestamp: string) => new Intl.DateTimeFormat("en", { hour: "numeric", minute: "2-digit", timeZone: "UTC" }).format(new Date(timestamp));

function MetricIcon({ type }: { type: "policy" | "actions" | "block" | "approval" }) {
  const paths = { policy: <><path d="M7 3.5h7l3 3V20a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1v-15a1.5 1.5 0 0 1 1-1.5Z" /><path d="M14 3.5V7h3M9 12h6" /></>, actions: <><path d="M12 3a9 9 0 1 0 9 9" /><path d="M12 7v5l3 2M17 3v4h4" /></>, block: <><path d="M12 9v4m0 4h.01M10.3 3.9 2.8 17a2 2 0 0 0 1.7 3h15a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0Z" /></>, approval: <><path d="M12 3 4.5 6v5c0 4.7 3.2 8.6 7.5 10 4.3-1.4 7.5-5.3 7.5-10V6L12 3Z" /><path d="m8.5 12 2.3 2.3 4.7-4.7" /></> };
  return <svg aria-hidden="true" className="size-4" fill="none" stroke="currentColor" strokeWidth="1.8" viewBox="0 0 24 24">{paths[type]}</svg>;
}

export default function DashboardPage() {
  const decisionsByAction = new Map(mockDecisions.map((decision) => [decision.action_id, decision]));
  const recentActions = [...mockActions].sort((a, b) => b.timestamp.localeCompare(a.timestamp)).slice(0, 5);
  const activePolicies = mockPolicies.filter((policy) => policy.status === "active");
  const blockedActions = mockDecisions.filter((decision) => decision.decision === "block");
  const pendingApprovals = mockDecisions.filter((decision) => decision.decision === "requires_approval");
  const flags = mockDecisions.filter((decision) => decision.decision !== "allow").slice(-3).reverse();
  const categoryCount = new Set(activePolicies.map((policy) => policy.category)).size;

  return <div className="space-y-10">
    <section className="flex flex-col justify-between gap-5 border-b border-slate-200/80 pb-8 sm:flex-row sm:items-end"><div><p className="text-xs font-medium uppercase tracking-[0.1em] text-indigo-600">Maplewood Home & Living</p><h2 className="mt-3 text-[clamp(30px,3vw,36px)] font-medium tracking-[-0.05em] text-slate-950">Agent governance, at a glance.</h2><p className="mt-3 max-w-2xl text-[15px] leading-7 text-slate-500">Every AI tool call is intercepted, evaluated against active policy, and held for human oversight when needed.</p></div><Link href="/actions" className="inline-flex h-11 items-center justify-center rounded-xl border border-slate-300 bg-white px-5 text-[14px] font-medium text-slate-700 transition-colors hover:border-slate-400 hover:bg-slate-50">View action log</Link></section>

    <section aria-label="Overview" className="grid divide-y divide-slate-200/90 border-y border-slate-200/90 py-6 sm:grid-cols-2 sm:divide-x sm:divide-y-0 xl:grid-cols-4"><StatCard label="Active policies" value={activePolicies.length} detail={`${mockPolicies.length - activePolicies.length} awaiting review`} tone="indigo" icon={<MetricIcon type="policy" />} /><StatCard label="Intercepted actions" value={mockActions.length} detail="All tool calls observed" icon={<MetricIcon type="actions" />} /><StatCard label="Blocked actions" value={blockedActions.length} detail="Violations prevented" tone="rose" icon={<MetricIcon type="block" />} /><StatCard label="Pending approvals" value={pendingApprovals.length} detail="Human decisions needed" tone="amber" icon={<MetricIcon type="approval" />} /></section>

    <section className="grid gap-10 xl:grid-cols-[minmax(0,1fr)_280px]"><div><div className="flex items-end justify-between border-b border-slate-200/80 pb-4"><div><p className="text-xs font-medium uppercase tracking-[0.1em] text-slate-500">Live activity</p><h3 className="mt-2 text-[18px] font-medium tracking-[-0.025em] text-slate-950">Recent intercepted actions</h3></div><Link href="/actions" className="text-[14px] font-medium text-indigo-700 hover:text-indigo-800">Open feed</Link></div><div className="divide-y divide-slate-100">{recentActions.map((action) => { const decision = decisionsByAction.get(action.action_id); return <div key={action.action_id} className="grid gap-2 py-5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2.5"><p className="text-[15px] font-medium text-slate-900">{titleForAction(action.action)}</p>{decision && <DecisionBadge decision={decision.decision} />}</div><p className="mt-1.5 truncate text-[14px] text-slate-500"><span className="font-medium text-slate-700">{action.agent_id}</span><span className="mx-1.5 text-slate-300">/</span>{action.tool}<span className="mx-1.5 text-slate-300">/</span>{action.context?.reason ?? "No reason supplied"}</p></div><time className="text-[13px] font-medium tabular-nums text-slate-400">{formatTime(action.timestamp)} UTC</time></div>; })}</div></div>
      <aside className="border-l border-slate-200/80 pl-0 xl:pl-7"><p className="text-xs font-medium uppercase tracking-[0.1em] text-slate-500">Coverage</p><h3 className="mt-2 text-lg font-medium tracking-[-0.025em] text-slate-950">Enforcement readiness</h3><p className="mt-2 text-sm leading-6 text-slate-500">{categoryCount} categories represented by active rules.</p><div className="mt-7"><div className="flex items-baseline justify-between"><span className="text-sm text-slate-600">Policies active</span><span className="text-sm font-medium tabular-nums text-slate-900">{activePolicies.length}/{mockPolicies.length}</span></div><div className="mt-3 h-px bg-slate-200"><div className="h-px bg-indigo-600" style={{ width: `${(activePolicies.length / mockPolicies.length) * 100}%` }} /></div></div><p className="mt-7 border-t border-slate-200 pt-5 text-sm leading-6 text-slate-500"><span className="font-medium text-slate-700">Deterministic by design.</span> The rule engine makes the final enforcement decision; explanations support human understanding.</p></aside>
    </section>

    <section className="grid gap-10 border-t border-slate-200/80 pt-8 lg:grid-cols-2"><div><div className="flex items-end justify-between"><div><p className="text-xs font-medium uppercase tracking-[0.1em] text-slate-500">Priority queue</p><h3 className="mt-2 text-lg font-medium tracking-[-0.025em] text-slate-950">Needs attention</h3></div><Link href="/approvals" className="text-sm font-medium text-indigo-700 hover:text-indigo-800">Review approvals</Link></div><div className="mt-4 divide-y divide-slate-100">{flags.map((decision) => { const action = mockActions.find((item) => item.action_id === decision.action_id); return <div key={decision.action_id} className="py-4"><div className="flex flex-wrap items-center gap-2.5"><p className="text-sm font-medium text-slate-900">{action ? titleForAction(action.action) : "Policy decision"}</p><DecisionBadge decision={decision.decision} /></div><p className="mt-2 text-sm leading-6 text-slate-500">{decision.reason}</p>{decision.required_approval && <p className="mt-2 text-xs font-medium capitalize text-amber-700">Required approver: {decision.required_approval.replace("_", " ")}</p>}</div>; })}</div></div>
      <div className="border-l border-slate-200/80 pl-0 lg:pl-8"><p className="text-xs font-medium uppercase tracking-[0.1em] text-indigo-600">Gateway workflow</p><h3 className="mt-2 text-lg font-medium tracking-[-0.025em] text-slate-950">A clear control path for every action</h3><ol className="mt-6 space-y-5">{[["01", "Agent request", "An agent submits an MCP tool call."], ["02", "Policy evaluation", "Active rules are matched against the canonical action."], ["03", "Enforcement decision", "The gateway allows, blocks, or requests approval."]].map(([number, title, description], index) => <li key={number} className="relative flex gap-4"><span className="font-mono text-xs font-medium text-indigo-600">{number}</span><div className={index < 2 ? "relative pb-5 before:absolute before:left-[-29px] before:top-6 before:h-full before:w-px before:bg-slate-200" : ""}><p className="text-sm font-medium text-slate-800">{title}</p><p className="mt-1 text-sm leading-6 text-slate-500">{description}</p></div></li>)}</ol></div>
    </section>
  </div>;
}
